import turtle

size = 150

for i in range(150):
    turtle.shape("turtle")
    turtle.color("red")
    turtle.speed(11)
    turtle.circle(size)
    size -= 1
    turtle.shape("turtle")
    turtle.color("blue")
    turtle.speed(11)
    turtle.circle(size)
    size -= 1

turtle.speed(1)
turtle.forward(170)
turtle.left(90)
turtle.forward(300)
turtle.right(90)
turtle.forward(20)
turtle.right(90)
turtle.forward(20)
turtle.write("T H E  T U R T L E  I S  C O M I N G !")
turtle.forward(20)
turtle.write("D O N T  G O  T O  S L E E P  T O M M O R O W !")
turtle.forward(20)
turtle.write("O H  L A W D  H E  C O M E T H !")
turtle.forward(20)
turtle.write("H I D E  Y O U R  V A L U B L E S!")
turtle.forward(20)
turtle.write("D O N T  T R Y  T O  R U N !")
turtle.forward(20)
turtle.write("Q U I C K L Y !")
turtle.forward(20)
turtle.write("H I D E  A T  Y O U R  L O C A L  F R E E Z E R !")
turtle.forward(20)
turtle.write("Y O U  H A V E ")
turtle.forward(20)
turtle.write("F I V E  S E C O N D S")
turtle.forward(20)
turtle.write("T O  E N T E R")
turtle.forward(20)
turtle.write("Y O U R  C R E D I T  C A R D  D E T A I L S")
turtle.forward(20)
turtle.write("A N D  T H E  L A S T  4  N U M B E R S  O N  T H E  B A C K")
turtle.forward(20)
turtle.write("M A K E  S U R E  T O  A L S O  B U Y")
turtle.forward(20)
turtle.write("30  S T E A M  G I F T  C A R D S  F O R  M E")
turtle.forward(20)
turtle.write("O R  E L S E  M . R .  T U R T L E")
turtle.forward(20)
turtle.write("N O T E : T H I S  I S  J U S T  A  J O K E")
turtle.forward(999)
turtle.exitonclick()
